"""Add owned_book_copies table

Revision ID: a3e5ffb9c0da
Revises: fd8620657c1b
Create Date: 2018-05-13 12:30:25.820052

"""

# revision identifiers, used by Alembic.
revision = 'a3e5ffb9c0da'
down_revision = 'fd8620657c1b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owned_book_copies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['borrower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('owner_id', 'book_id', 'id')
    )
    op.drop_table('book_users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_users',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='book_users_book_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='book_users_user_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'user_id', name='book_users_pkey')
    )
    op.drop_table('owned_book_copies')
    ### end Alembic commands ###
