"""empty message

Revision ID: b6673fe8ed45
Revises: 13793c6c6527
Create Date: 2018-03-03 18:53:55.197145

"""

# revision identifiers, used by Alembic.
revision = 'b6673fe8ed45'
down_revision = '13793c6c6527'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_books_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_books_id')
    )
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_users',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_id')
    )
    op.create_table('house_users',
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('house_id', 'user_id')
    )
    op.add_column('users', sa.Column('display_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'display_name')
    op.drop_table('house_users')
    op.drop_table('book_users')
    op.drop_table('houses')
    op.drop_table('books')
    ### end Alembic commands ###
