"""Add house_members and house_member_requests tables

Revision ID: ed1f0de54044
Revises: 69f292cab686
Create Date: 2018-10-24 20:16:04.699103

"""

# revision identifiers, used by Alembic.
revision = 'ed1f0de54044'
down_revision = '69f292cab686'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('house_membership_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('users_house_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'house_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('house_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.create_foreign_key('users_house_id_fkey', 'users', 'houses', ['house_id'], ['id'])
    op.drop_table('house_membership_requests')
    op.drop_table('house_members')
    # ### end Alembic commands ###
