"""Add indexing to Book column `google_books_id`

Revision ID: fd8620657c1b
Revises: c921b344e2f7
Create Date: 2018-04-06 17:30:43.883460

"""

# revision identifiers, used by Alembic.
revision = 'fd8620657c1b'
down_revision = 'c921b344e2f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_google_books_id'), 'books', ['google_books_id'], unique=True)
    op.drop_constraint('books_google_books_id_key', 'books', type_='unique')
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'display_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint('books_google_books_id_key', 'books', ['google_books_id'])
    op.drop_index(op.f('ix_books_google_books_id'), table_name='books')
    ### end Alembic commands ###
